meta:
  name: NetArchon
  version: 0.1.0
  date: "2020-06-01"

app:
  host: "0.0.0.0"
  port: 8443
  threaded: True

certificates:
  cert: services/app/certificates/cert.pem
  key: services/app/certificates/key.pem

paths:
  root: /projects/gitlab/netarchon
  database: db
  logs: logs
  certificates_dir: services/app/certificates

network:
  lan:
    name: enp2s0
    mac: 18:c0:4d:46:f4:11
    ip: "192.168.20.100"
    subnet_mask: "255.255.255.0"
    gateway: "192.168.20.1"
    cidr: "24"
    broadcast_ip: "192.168.20.255"
    family: inet
    role: lan

dns:
  host: "0.0.0.0"
  port: 53
  dns_servers: ["1.1.1.3", "1.0.0.3", "9.9.9.9", "149.112.112.112"]
  cache_ttl: 600
  blacklists: config/dns_control_list.json
  msg_size: 1232
  process_workers: 100
  external_workers: 300
  external_timeout: 15
  local_timeout: 0.2
  zones:
    home.lan:
      server: 192.168.20.100
      printer: 192.168.20.10

dhcp:
  interface: enp2s0
  host: "0.0.0.0"
  port: 67
  router_ip: "192.168.20.1"
  dns_ip: "192.168.20.100"
  ntp_server: "pool.ntp.org"
  ip_pool_start: "192.168.20.101"
  ip_pool_end: "192.168.20.254"
  lease_time_seconds: 1209600
  mtu: 1500

database:
  persistence_interval: 30
  blacklists_loading_interval: 30
  dhcp:
    stats:
      type: sqlite
      path: db/dhcp_stats.sqlite3
    leases:
      type: sqlite
      path: db/dhcp_leases.sqlite3
  dns:
    history:
      type: sqlite
      path: db/dns_history.sqlite3
      max_records: 1000
    stats:
      type: sqlite
      path: db/dns_stats.sqlite3

logging:
  levels:
    debug: DEBUG
    info: INFO
    warning: WARNING
    error: ERROR
    critical: CRITICAL
  formatters:
    default:
      format: "%(asctime)s.%(msecs)03d | %(levelname)s | %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      filename: ./logs/main.log
      maxBytes: 10485760
      backupCount: 2
      encoding: utf-8
      mode: a
      level: DEBUG
      formatter: default
  root:
    level: INFO
    handlers: [file]
