version: "3"

services:
  gateway-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - gateway-net
    environment:
      - INFLUXDB_HOST=influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    networks:
      - gateway-net

networks:
  gateway-net:
    driver: bridge
